# Exercícios

1. Crie um dataframe de tax_data_2016.csv que usa apenas as colunas específicas necessárias para ver se há diferenças por geografia e nível de renda na composição familiar.
Para fazer isso, selecione as colunas sobre grupo de renda, são elas: CEP (zipcode), status de declaração de imposto de renda (coluna mars1 para solteiro e MARS2 para casado), e  NUMDEP (número de dependentes).

In [1]:
import pandas as pd
pd.set_option("display.max_columns", 200)

In [18]:
path = '../dados/atividade1/us_tax_data_2016.csv'

df = pd.read_csv(path,encoding='ansi')
df_tax = df[['zipcode', 'mars1', 'MARS2', 'NUMDEP']]
df_tax.head()
df_tax

      zipcode   mars1   MARS2  NUMDEP
0           0  477700  105350  491310
1           0  211930  142340  360480
2           0   83420  137870  182880
3           0   29420  124060  130160
4           0   20240  188080  195990
...       ...     ...     ...     ...
2996    36584       0      30      30
2997    36584       0      30      30
2998    36584       0       0       0
2999    36585      80      20      90
3000    36585      40      30      60

[3001 rows x 4 columns]

2. Obtenha as primeiras 500 linhas em um dataframe chamado primeiras500. 
Em seguida obtenha as próximas 500 linhas em um dataframe proximas500. 
Para fazer isso, use os argumentos ``nrows`` e  ``skiprows`` para obter os registros corretos, 
``header`` para informar aos pandas que os dados não têm nomes de colunas e ``names`` para fornecer os nomes de colunas ausentes.     
Depois, nomeie as colunas em proximos500 fornecendo uma lista de colunas de primeiros500 para o argumento ``names``.
Use a função list() para obter nomes de coluna de primeiros500.

In [21]:
df.head(1)

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,NUMDEP,TOTAL_VITA,VITA,TCE,VITA_EIC,RAL,RAC,ELDERLY,A00100,N02650,A02650,N00200,A00200,N00300,A00300,N00600,A00600,N00650,A00650,N00700,A00700,N00900,A00900,N01000,A01000,N01400,A01400,N01700,A01700,SCHF,N02300,A02300,N02500,A02500,N26270,A26270,N02900,A02900,N03220,A03220,N03300,A03300,N03270,A03270,N03150,A03150,N03210,A03210,N03230,A03230,N03240,A03240,N04470,A04470,A00101,N17000,A17000,N18425,A18425,N18450,A18450,N18500,A18500,N18800,A18800,N18300,A18300,N19300,A19300,N19500,A19500,N19530,A19530,N19550,A19550,N19570,A19570,N19700,A19700,N20800,A20800,n21020,a21020,N04800,A04800,N05800,A05800,N09600,A09600,N05780,A05780,N07100,A07100,N07300,A07300,N07180,A07180,N07230,A07230,N07240,A07240,N07220,A07220,N07260,A07260,N09400,A09400,N85770,A85770,N85775,A85775,N09750,A09750,N10600,A10600,N59660,A59660,N59720,A59720,N11070,A11070,N10960,A10960,N11560,A11560,N06500,A06500,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
0,1,AL,0,1,815440,477700,105350,221200,440830,1296920,491310,24730,16610,8130,5440,31550,225140,150920,10610343,815440,10787121,651680,8466376,90040,57551,42420,74527,38170,51048,11830,5328,144430,765184,34770,20594,38510,240402,104980,1038534,8310,22770,65220,37560,73490,7900,17497,145820,176778,1340,308,40,387,8630,32058,1730,5091,17110,14893,6620,18836,20,103,48600,699784,757559,34710,280423,18450,19585,22670,18822,22600,21511,25020,5950,46930,74541,20950,109734,190,563,330,150,2680,3326,200,142,36370,104574,17910,82471,400,2329,320790,1806830,325650,195415,0,0,18830,6579,101150,34290,1760,68,6620,2205,27490,15002,32490,5582,28940,8858,1140,471,113880,155301,54520,230494,56460,231566,18020,10199,755160,2119297,363420,1097024,333760,981026,229900,291625,61350,57108,28510,14474,254700,160665,367320,330066,0,0,0,0,63420,51444,711580,1831661

In [22]:
colunas = ['STATEFIPS', 'STATE', 'zipcode', 'agi_stub', 'N1', 'mars1', 'MARS2', 'MARS4', 'PREP', 'N2', 'NUMDEP', 'TOTAL_VITA', 'VITA', 'TCE', 'VITA_EIC', 'RAL', 'RAC', 'ELDERLY', 'A00100', 'N02650', 'A02650', 'N00200', 'A00200', 'N00300', 'A00300', 'N00600', 'A00600', 'N00650', 'A00650', 'N00700', 'A00700', 'N00900', 'A00900', 'N01000', 'A01000', 'N01400', 'A01400', 'N01700', 'A01700', 'SCHF', 'N02300', 'A02300', 'N02500', 'A02500', 'N26270', 'A26270', 'N02900', 'A02900', 'N03220', 'A03220', 'N03300', 'A03300', 'N03270', 'A03270', 'N03150', 'A03150', 'N03210', 'A03210', 'N03230', 'A03230', 'N03240', 'A03240', 'N04470', 'A04470', 'A00101', 'N17000', 'A17000', 'N18425', 'A18425', 'N18450', 'A18450', 'N18500', 'A18500', 'N18800', 'A18800', 'N18300', 'A18300', 'N19300', 'A19300', 'N19500', 'A19500', 'N19530', 'A19530', 'N19550', 'A19550', 'N19570', 'A19570', 'N19700', 'A19700', 'N20800', 'A20800', 'n21020', 'a21020', 'N04800', 'A04800', 'N05800', 'A05800', 'N09600', 'A09600', 'N05780', 'A05780', 'N07100', 'A07100', 'N07300', 'A07300', 'N07180', 'A07180', 'N07230', 'A07230', 'N07240', 'A07240', 'N07220', 'A07220', 'N07260', 'A07260', 'N09400', 'A09400', 'N85770', 'A85770', 'N85775', 'A85775', 'N09750', 'A09750', 'N10600', 'A10600', 'N59660', 'A59660', 'N59720', 'A59720', 'N11070', 'A11070', 'N10960', 'A10960', 'N11560', 'A11560', 'N06500', 'A06500', 'N10300', 'A10300', 'N85530', 'A85530', 'N85300', 'A85300', 'N11901', 'A11901', 'N11902', 'A11902']
df2 = pd.read_csv(path,encoding='ansi', header=None, names=colunas)
df2.head(1)

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,NUMDEP,TOTAL_VITA,VITA,TCE,VITA_EIC,RAL,RAC,ELDERLY,A00100,N02650,A02650,N00200,A00200,N00300,A00300,N00600,A00600,N00650,A00650,N00700,A00700,N00900,A00900,N01000,A01000,N01400,A01400,N01700,A01700,SCHF,N02300,A02300,N02500,A02500,N26270,A26270,N02900,A02900,N03220,A03220,N03300,A03300,N03270,A03270,N03150,A03150,N03210,A03210,N03230,A03230,N03240,A03240,N04470,A04470,A00101,N17000,A17000,N18425,A18425,N18450,A18450,N18500,A18500,N18800,A18800,N18300,A18300,N19300,A19300,N19500,A19500,N19530,A19530,N19550,A19550,N19570,A19570,N19700,A19700,N20800,A20800,n21020,a21020,N04800,A04800,N05800,A05800,N09600,A09600,N05780,A05780,N07100,A07100,N07300,A07300,N07180,A07180,N07230,A07230,N07240,A07240,N07220,A07220,N07260,A07260,N09400,A09400,N85770,A85770,N85775,A85775,N09750,A09750,N10600,A10600,N59660,A59660,N59720,A59720,N11070,A11070,N10960,A10960,N11560,A11560,N06500,A06500,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
0,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,NUMDEP,TOTAL_VITA,VITA,TCE,VITA_EIC,RAL,RAC,ELDERLY,A00100,N02650,A02650,N00200,A00200,N00300,A00300,N00600,A00600,N00650,A00650,N00700,A00700,N00900,A00900,N01000,A01000,N01400,A01400,N01700,A01700,SCHF,N02300,A02300,N02500,A02500,N26270,A26270,N02900,A02900,N03220,A03220,N03300,A03300,N03270,A03270,N03150,A03150,N03210,A03210,N03230,A03230,N03240,A03240,N04470,A04470,A00101,N17000,A17000,N18425,A18425,N18450,A18450,N18500,A18500,N18800,A18800,N18300,A18300,N19300,A19300,N19500,A19500,N19530,A19530,N19550,A19550,N19570,A19570,N19700,A19700,N20800,A20800,n21020,a21020,N04800,A04800,N05800,A05800,N09600,A09600,N05780,A05780,N07100,A07100,N07300,A07300,N07180,A07180,N07230,A07230,N07240,A07240,N07220,A07220,N07260,A07260,N09400,A09400,N85770,A85770,N85775,A85775,N09750,A09750,N10600,A10600,N59660,A59660,N59720,A59720,N11070,A11070,N10960,A10960,N11560,A11560,N06500,A06500,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902

In [39]:
primeiras500 = pd.read_csv(path, encoding='ansi', nrows=500)
col_names = list(primeiras500)

batch_size = 500

for i in range(0,500):
    proximas500 = pd.read_csv(path, nrows=batch_size, skiprows=i*batch_size, header=None, names=col_names)
proximas500.head()

Empty DataFrame
Columns: [STATEFIPS, STATE, zipcode, agi_stub, N1, mars1, MARS2, MARS4, PREP, N2, NUMDEP, TOTAL_VITA, VITA, TCE, VITA_EIC, RAL, RAC, ELDERLY, A00100, N02650, A02650, N00200, A00200, N00300, A00300, N00600, A00600, N00650, A00650, N00700, A00700, N00900, A00900, N01000, A01000, N01400, A01400, N01700, A01700, SCHF, N02300, A02300, N02500, A02500, N26270, A26270, N02900, A02900, N03220, A03220, N03300, A03300, N03270, A03270, N03150, A03150, N03210, A03210, N03230, A03230, N03240, A03240, N04470, A04470, A00101, N17000, A17000, N18425, A18425, N18450, A18450, N18500, A18500, N18800, A18800, N18300, A18300, N19300, A19300, N19500, A19500, N19530, A19530, N19550, A19550, N19570, A19570, N19700, A19700, N20800, A20800, n21020, a21020, N04800, A04800, N05800, A05800, N09600, A09600, N05780, ...]
Index: []

In [38]:
primeiras500.info()
proximas500.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Columns: 147 entries, STATEFIPS to A11902
dtypes: int64(146), object(1)
memory usage: 572.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Columns: 147 entries, STATEFIPS to A11902
dtypes: object(147)
memory usage: 62.0+ bytes

In [29]:
primeiras500.head(1)

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,NUMDEP,TOTAL_VITA,VITA,TCE,VITA_EIC,RAL,RAC,ELDERLY,A00100,N02650,A02650,N00200,A00200,N00300,A00300,N00600,A00600,N00650,A00650,N00700,A00700,N00900,A00900,N01000,A01000,N01400,A01400,N01700,A01700,SCHF,N02300,A02300,N02500,A02500,N26270,A26270,N02900,A02900,N03220,A03220,N03300,A03300,N03270,A03270,N03150,A03150,N03210,A03210,N03230,A03230,N03240,A03240,N04470,A04470,A00101,N17000,A17000,N18425,A18425,N18450,A18450,N18500,A18500,N18800,A18800,N18300,A18300,N19300,A19300,N19500,A19500,N19530,A19530,N19550,A19550,N19570,A19570,N19700,A19700,N20800,A20800,n21020,a21020,N04800,A04800,N05800,A05800,N09600,A09600,N05780,A05780,N07100,A07100,N07300,A07300,N07180,A07180,N07230,A07230,N07240,A07240,N07220,A07220,N07260,A07260,N09400,A09400,N85770,A85770,N85775,A85775,N09750,A09750,N10600,A10600,N59660,A59660,N59720,A59720,N11070,A11070,N10960,A10960,N11560,A11560,N06500,A06500,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
0,1,AL,35565,4,270,0,250,0,210,790,280,0,0,0,0,0,30,70,22905,270,23131,240,18964,130,85,40,103,40,79,60,49,60,554,30,169,30,359,50,1408,20,30,109,60,1071,0,0,100,226,30,9,0,0,0,0,0,0,40,48,0,0,0,0,90,1857,8128,30,161,90,325,0,0,80,47,90,23,90,425,80,466,0,0,0,0,40,38,0,0,80,365,50,447,0,0,270,15662,270,2118,0,0,0,0,150,265,0,0,20,8,40,64,0,0,110,186,20,5,40,107,0,0,0,0,0,0,260,2573,0,0,0,0,0,0,30,33,0,0,260,1854,260,1978,0,0,0,0,50,222,210,794

In [30]:
proximas500.head(1)

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,NUMDEP,TOTAL_VITA,VITA,TCE,VITA_EIC,RAL,RAC,ELDERLY,A00100,N02650,A02650,N00200,A00200,N00300,A00300,N00600,A00600,N00650,A00650,N00700,A00700,N00900,A00900,N01000,A01000,N01400,A01400,N01700,A01700,SCHF,N02300,A02300,N02500,A02500,N26270,A26270,N02900,A02900,N03220,A03220,N03300,A03300,N03270,A03270,N03150,A03150,N03210,A03210,N03230,A03230,N03240,A03240,N04470,A04470,A00101,N17000,A17000,N18425,A18425,N18450,A18450,N18500,A18500,N18800,A18800,N18300,A18300,N19300,A19300,N19500,A19500,N19530,A19530,N19550,A19550,N19570,A19570,N19700,A19700,N20800,A20800,n21020,a21020,N04800,A04800,N05800,A05800,N09600,A09600,N05780,A05780,N07100,A07100,N07300,A07300,N07180,A07180,N07230,A07230,N07240,A07240,N07220,A07220,N07260,A07260,N09400,A09400,N85770,A85770,N85775,A85775,N09750,A09750,N10600,A10600,N59660,A59660,N59720,A59720,N11070,A11070,N10960,A10960,N11560,A11560,N06500,A06500,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
0,1,AL,35565,4,270,0,250,0,210,790,280,0,0,0,0,0,30,70,22905,270,23131,240,18964,130,85,40,103,40,79,60,49,60,554,30,169,30,359,50,1408,20,30,109,60,1071,0,0,100,226,30,9,0,0,0,0,0,0,40,48,0,0,0,0,90,1857,8128,30,161,90,325,0,0,80,47,90,23,90,425,80,466,0,0,0,0,40,38,0,0,80,365,50,447,0,0,270,15662,270,2118,0,0,0,0,150,265,0,0,20,8,40,64,0,0,110,186,20,5,40,107,0,0,0,0,0,0,260,2573,0,0,0,0,0,0,30,33,0,0,260,1854,260,1978,0,0,0,0,50,222,210,794

3. Carregue o arquivo tax_data_2016.csv, visualize o atributo dtypes do dataframe e observe os tipos de dados de CEP e agi_stub.

In [2]:
path = '../dados/atividade1/us_tax_data_2016.csv'

df = pd.read_csv(path,encoding='ansi')
df.dtypes

STATEFIPS     int64
STATE        object
zipcode       int64
agi_stub      int64
N1            int64
              ...
A85300        int64
N11901        int64
A11901        int64
N11902        int64
A11902        int64
Length: 147, dtype: object

4. Você deve ter observado que a coluna agi_stub contém números que correspondem a categorias de renda, e CEP tem valores de 5 dígitos que devem ser strings -- tratá-los como inteiros significa que perdemos 0s iniciais, que são significativos. 
Defina os tipos de dados corretos criando um dicionario chamado null_values, especificando que 0s na coluna CEP devem ser considerados valores NA.
Depois, carregue tax_data_2016.csv, usando o argumento na_values e o dicionário para garantir que CEPs inválidos sejam tratados como ausentes.

In [6]:
null_values = {"zipcode":[0, 'NA']}
tax_data = pd.read_csv(path, na_values=null_values)
tax_data.head()

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,NUMDEP,TOTAL_VITA,VITA,TCE,VITA_EIC,RAL,RAC,ELDERLY,A00100,N02650,A02650,N00200,A00200,N00300,A00300,N00600,A00600,N00650,A00650,N00700,A00700,N00900,A00900,N01000,A01000,N01400,A01400,N01700,A01700,SCHF,N02300,A02300,N02500,A02500,N26270,A26270,N02900,A02900,N03220,A03220,N03300,A03300,N03270,A03270,N03150,A03150,N03210,A03210,N03230,A03230,N03240,A03240,N04470,A04470,A00101,N17000,A17000,N18425,A18425,N18450,A18450,N18500,A18500,N18800,A18800,N18300,A18300,N19300,A19300,N19500,A19500,N19530,A19530,N19550,A19550,N19570,A19570,N19700,A19700,N20800,A20800,n21020,a21020,N04800,A04800,N05800,A05800,N09600,A09600,N05780,A05780,N07100,A07100,N07300,A07300,N07180,A07180,N07230,A07230,N07240,A07240,N07220,A07220,N07260,A07260,N09400,A09400,N85770,A85770,N85775,A85775,N09750,A09750,N10600,A10600,N59660,A59660,N59720,A59720,N11070,A11070,N10960,A10960,N11560,A11560,N06500,A06500,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
0,1,AL,NaN,1,815440,477700,105350,221200,440830,1296920,491310,24730,16610,8130,5440,31550,225140,150920,10610343,815440,10787121,651680,8466376,90040,57551,42420,74527,38170,51048,11830,5328,144430,765184,34770,20594,38510,240402,104980,1038534,8310,22770,65220,37560,73490,7900,17497,145820,176778,1340,308,40,387,8630,32058,1730,5091,17110,14893,6620,18836,20,103,48600,699784,757559,34710,280423,18450,19585,22670,18822,22600,21511,25020,5950,46930,74541,20950,109734,190,563,330,150,2680,3326,200,142,36370,104574,17910,82471,400,2329,320790,1806830,325650,195415,0,0,18830,6579,101150,34290,1760,68,6620,2205,27490,15002,32490,5582,28940,8858,1140,471,113880,155301,54520,230494,56460,231566,18020,10199,755160,2119297,363420,1097024,333760,981026,229900,291625,61350,57108,28510,14474,254700,160665,367320,330066,0,0,0,0,63420,51444,711580,1831661
1,1,AL,NaN,2,495830,211930,142340,128890,272440,996240,360480,10890,7100,3780,280,11770,118460,109680,17839904,495830,18020908,427840,14690098,89460,63622,39400,94307,35060,67289,47330,26083,65350,258861,31040,50118,36020,348074,100030,1812761,8920,15170,45546,91310,605042,10340,69499,96260,181004,14260,3476,90,1037,7570,37604,7300,24316,41490,43047,2340,5833,60,574,103560,1579761,3947654,47510,339474,74730,127434,25830,32861,66650,58178,64360,17611,102740,243301,60550,312252,1070,3508,1290,590,19320,23659,300,236,85920,337353,44430,292180,2290,14634,474930,8739820,473360,1067785,0,0,17200,13087,216450,191023,6320,291,30880,17180,43580,45248,77770,14984,122630,108314,12690,6759,38490,84581,24960,96905,27540,110068,21690,14515,485140,2062531,138800,291932,115640,245939,102530,144943,33880,30970,5140,4460,375320,877407,398050,984297,0,0,0,0,74090,110889,416090,1173463
2,1,AL,NaN,3,263390,83420,137870,36340,154880,584000,182880,2480,1270,1210,0,150,41910,75570,16193076,263390,16351320,225610,12476022,80410,64816,38990,121115,35340,89415,58720,40132,41390,259064,31240,85650,29450,388970,73030,1836648,8470,7460,24614,63740,961406,11580,126140,69510,158244,8520,2146,190,1995,5530,35869,5340,22892,29110,31929,2150,4834,70,442,100110,1736214,6253051,29890,236177,80920,208782,17080,27736,78160,75404,68320,19479,99920,337719,71760,405379,1670,5677,2670,1568,21170,27432,690,660,85510,407422,37110,278272,2400,18992,262070,10338819,261500,1429944,40,96,4180,7590,113150,165544,9150,684,18100,9762,22780,29166,18710,2977,75270,113174,9740,5867,27370,68645,2400,8954,5780,22602,4510,4481,259650,1769024,70,24,20,7,9560,12495,16820,15588,0,0,249560,1264586,253180,1349246,0,0,0,0,64000,143060,195130,543284
3,1,AL,NaN,4,167190,29420,124060,10610,99700,421720,130160,620,390,230,0,0,18560,51540,14513312,167190,14646693,144290,10900188,67750,59882,33700,124605,30700,94076,53210,42499,28910,240845,27320,103892,22930,411954,53260,1666592,5510,3850,13372,42870,874160,8780,145281,49910,133381,8580,2323,110,1986,2640,20394,3040,15828,20610,23854,360,766,140,353,80100,1575109,7012174,16830,141086,67360,237633,10910,21257,69930,78523,58540,18167,79980,362811,64200,412166,610,2061,1550,884,17450,24277,570,850,70730,394630,24780,202113,960,10141,166900,10176894,166580,1480117,260,609,520,1445,74870,127722,7530,1507,15060,8574,17250,22630,0,0,53970,88853,5770,2765,19550,56524,20,84,840,3148,510,724,165540,1693476,0,0,0,0,130,197,12040,11117,0,0,165330,1352397,165830,1425430,0,0,0,0,45020,128920,117410,381329
4,1,AL,NaN,5,217440,20240,188080,4880,129410,601040,195990,680,660,20,0,0,11620,68080,29375736,217440,29696755,193550,21806247,116090,145219,69540,375343,64870,300101,110430,118782,43180,684832,59160,506542,34750,909488,74160,2988298,8180,2280,8380,50010,1195287,24980,828015,77820,321019,12040,3192,1310,21562,7290,65730,5090,29860,22870,24745,3450,7047,780,8960,152000,3605095,21234787,13430,136781,137690,760514,10940,27202,141070,216729,117980,44270,151920,1065202,128400,1000072,2380,8573,7140,3672,3440,2859,3020,5618,139560,982689,34030,298272,2890,37716,217250,22511460,216970,3890612,1930,4531,140,580,95820,130089,19270,3949,21690,12377,20970,29469,0,0,46670,62728,6750,2896,31130,127140,0,0,160,717,180,360,215570,4072975,0,0,0,0,0,0,18770,17844,0,0,216500,3760298,216720,3922449,390,155,60,19,82940,423629,126130,506526

5. Leia o arquivo fcc_survey.xlsx, atribua-o à variável survey_responses e imprima os primeiros registros de survey_responses.

In [5]:
path_xlsx = '../dados/aula3/fcc_survey.xlsx'
survey_responses = pd.read_excel(path_xlsx)
survey_responses.head()

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampMonthsAgo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventBootcamp,CodeEventCoffee,CodeEventConferences,CodeEventDjangoGirls,CodeEventGameJam,CodeEventGirlDev,CodeEventHackathons,CodeEventMeetup,CodeEventNodeSchool,CodeEventNone,CodeEventOther,CodeEventRailsBridge,CodeEventRailsGirls,CodeEventStartUpWknd,CodeEventWomenCode,CodeEventWorkshop,CommuteTime,CountryCitizen,CountryLive,EmploymentField,EmploymentFieldOther,EmploymentStatus,EmploymentStatusOther,ExpectedEarning,FinanciallySupporting,Gender,HasChildren,HasDebt,HasFinancialDependents,HasHighSpdInternet,HasHomeMortgage,HasServedInMilitary,HasStudentDebt,HomeMortgageOwe,HoursLearning,ID.x,ID.y,Income,IsEthnicMinority,IsReceiveDiabilitiesBenefits,IsSoftwareDev,IsUnderEmployed,JobApplyWhen,JobPref,JobRelocateYesNo,JobRoleInterest,JobRoleInterestOther,JobWherePref,LanguageAtHome,MaritalStatus,MoneyForLearning,MonthsProgramming,NetworkID,Part1EndTime,Part1StartTime,Part2EndTime,Part2StartTime,PodcastChangeLog,PodcastCodeNewbie,PodcastCodingBlocks,PodcastDeveloperTea,PodcastDotNetRocks,PodcastHanselminutes,PodcastJSJabber,PodcastJsAir,PodcastNone,PodcastOther,PodcastProgrammingThrowDown,PodcastRubyRogues,PodcastSEDaily,PodcastShopTalk,PodcastTalkPython,PodcastWebAhead,ResourceBlogs,ResourceBooks,ResourceCodeWars,ResourceCodecademy,ResourceCoursera,ResourceDevTips,ResourceEdX,ResourceEggHead,ResourceFCC,ResourceGoogle,ResourceHackerRank,ResourceKhanAcademy,ResourceLynda,ResourceMDN,ResourceOdinProj,ResourceOther,ResourcePluralSight,ResourceReddit,ResourceSkillCrush,ResourceSoloLearn,ResourceStackOverflow,ResourceTreehouse,ResourceUdacity,ResourceUdemy,ResourceW3Schools,ResourceYouTube,SchoolDegree,SchoolMajor,StudentDebtOwe
0,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,United States of America,United States of America,office and administrative support,NaN,Employed for wages,NaN,NaN,0.0,male,0.0,1.0,1.0,1.0,0.0,0.0,1.0,NaN,30.0,cef35615d61b202f1dc794ef2746df14,48fd66e15301df9727e13e6e80aef941,32000.0,0.0,0.0,0.0,1.0,NaN,freelance,NaN,NaN,NaN,NaN,English,married or domestic partnership,0.0,1.0,2c6f0af42c,2016-03-29 21:24:53,2016-03-29 21:23:13,2016-03-29 21:27:25,2016-03-29 21:24:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,20000.0
1,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,United States of America,United States of America,food and beverage,NaN,Employed for wages,NaN,50000.0,NaN,male,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,30.0,323e5a113644d18185c743c241407754,a8cd67193184084b1e32b362225bf280,15000.0,0.0,0.0,0.0,1.0,Within the next 6 months,work for a startup,1.0,Front-End Web Developer,NaN,in an office with other developers,English,NaN,20.0,2.0,d048ac774d,2016-03-29 21:27:09,2016-03-29 21:24:59,2016-03-29 21:29:10,2016-03-29 21:27:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Front-end happy hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"some college credit, no degree",NaN,NaN
2,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,United States of America,United States of America,finance,NaN,Employed for wages,NaN,NaN,NaN,male,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,20.0,b29a1027e5cd062e654a63764157461d,129b4479808fe006e768502b957a0c52,48000.0,0.0,0.0,0.0,0.0,NaN,start your own business,NaN,NaN,NaN,NaN,English,NaN,50.0,24.0,241513bbbe,2016-03-29 21:27:11,2016-03-29 21:25:37,2016-03-29 21:28:21,2016-03-29 21:27:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high school diploma or equivalent (GED),NaN,NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,45.0,United States of America,United States of America,"arts, entertainment, sports, or media",NaN,Employed for wages,NaN,65000.0,NaN,female,NaN,1.0,0.0,1.0,0.0,0.0,1.0,NaN,20.0,04a11e4bcb573a1261eb0d9948d32637,7313b696ac8f0517a3d0ec7725039bb2,43000.0,0.0,0.0,0.0,1.0,Within the next 6 months,work for a startup,NaN,Front-End Web Developer,NaN,from home,English,NaN,100.0,3.0,809298000000000071062979228803985833984,2016-03-29 21:28:47,2016-03-29 21:21:37,2016-03-29 21:30:51,2016-03-29 21:28:51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bachelor's degree,Cinematography And Film,7000.0
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,United States of America,United States of America,education,NaN,Employed for wages,NaN,45000.0,NaN,female,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN,25.0,9368291c93d5d5f5c8cdb1a575e18bec,d0f75544984896ccfd361af6d9b26047,6000.0,1.0,0.0,0.0,1.0,Within the next 6 months,work for a medium-sized company,1.0,Full-Stack Web Developer,NaN,in an office with other developers,Khmer,NaN,1300.0,48.0,cdc466b1ee,2016-03-29 21:29:27,2016-03-29 21:26:22,2016-03-29 21:31:54,2016-03-29 21:29:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,NaN

6. Crie uma string chamada col_string, especificando que os pandas devem carregar a coluna AD e o intervalo AW até BA.
Carregue fcc_survey.xlsx, definindo ``skiprows`` e ``usecols`` para ignorar as duas primeiras linhas e obter apenas as colunas em col_string.
Visualize os nomes das colunas selecionadas no dataframe resultante.

In [11]:
col_string = "AD, AW:BA"
survey = pd.read_excel(path_xlsx,
                       skiprows=2,
                       usecols=col_string)
list(survey)

['United States of America.1', 15000, '0.4', '0.5', '0.6', '1.1']

7. Crie um dataframe a partir do arquivo `fcc_survey.xlsx` passando a posição da segunda aba para ``sheet_name``.

In [10]:
survey = pd.read_excel(path_xlsx,
                       sheet_name=1)
survey.head()

,Age,AttendedBootcamp,BootcampFinish,BootcampLoanYesNo,BootcampName,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventConferences,CodeEventDjangoGirls,CodeEventFCC,CodeEventGameJam,CodeEventGirlDev,CodeEventHackathons,CodeEventMeetup,CodeEventNodeSchool,CodeEventNone,CodeEventOther,CodeEventRailsBridge,CodeEventRailsGirls,CodeEventStartUpWknd,CodeEventWkdBootcamps,CodeEventWomenCode,CodeEventWorkshops,CommuteTime,CountryCitizen,CountryLive,EmploymentField,EmploymentFieldOther,EmploymentStatus,EmploymentStatusOther,ExpectedEarning,FinanciallySupporting,FirstDevJob,Gender,GenderOther,HasChildren,HasDebt,HasFinancialDependents,HasHighSpdInternet,HasHomeMortgage,HasServedInMilitary,HasStudentDebt,HomeMortgageOwe,HoursLearning,ID.x,ID.y,Income,IsEthnicMinority,IsReceiveDisabilitiesBenefits,IsSoftwareDev,IsUnderEmployed,JobApplyWhen,JobInterestBackEnd,JobInterestDataEngr,JobInterestDataSci,JobInterestDevOps,JobInterestFrontEnd,JobInterestFullStack,JobInterestGameDev,JobInterestInfoSec,JobInterestMobile,JobInterestOther,JobInterestProjMngr,JobInterestQAEngr,JobInterestUX,JobPref,JobRelocateYesNo,JobRoleInterest,JobWherePref,LanguageAtHome,MaritalStatus,MoneyForLearning,MonthsProgramming,NetworkID,Part1EndTime,Part1StartTime,Part2EndTime,Part2StartTime,PodcastChangeLog,PodcastCodeNewbie,PodcastCodePen,PodcastDevTea,PodcastDotNET,PodcastGiantRobots,PodcastJSAir,PodcastJSJabber,PodcastNone,PodcastOther,PodcastProgThrowdown,PodcastRubyRogues,PodcastSEDaily,PodcastSERadio,PodcastShopTalk,PodcastTalkPython,PodcastTheWebAhead,ResourceCodecademy,ResourceCodeWars,ResourceCoursera,ResourceCSS,ResourceEdX,ResourceEgghead,ResourceFCC,ResourceHackerRank,ResourceKA,ResourceLynda,ResourceMDN,ResourceOdinProj,ResourceOther,ResourcePluralSight,ResourceSkillcrush,ResourceSO,ResourceTreehouse,ResourceUdacity,ResourceUdemy,ResourceW3S,SchoolDegree,SchoolMajor,StudentDebtOwe,YouTubeCodeCourse,YouTubeCodingTrain,YouTubeCodingTut360,YouTubeComputerphile,YouTubeDerekBanas,YouTubeDevTips,YouTubeEngineeredTruth,YouTubeFCC,YouTubeFunFunFunction,YouTubeGoogleDev,YouTubeLearnCode,YouTubeLevelUpTuts,YouTubeMIT,YouTubeMozillaHacks,YouTubeOther,YouTubeSimplilearn,YouTubeTheNewBoston
0,27.0,0.0,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15 to 29 minutes,Canada,Canada,software development and IT,NaN,Employed for wages,NaN,NaN,NaN,NaN,female,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN,15.0,02d9465b21e8bd09374b0066fb2d5614,eb78c1c3ac6cd9052aec557065070fbf,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,start your own business,NaN,NaN,NaN,English,married or domestic partnership,150.0,6.0,6f1fbc6b2b,2017-03-09 00:36:22,2017-03-09 00:32:59,2017-03-09 00:59:46,2017-03-09 00:36:26,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,"some college credit, no degree",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,34.0,0.0,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,United States of America,NaN,NaN,Not working but looking for work,NaN,35000.0,NaN,NaN,male,NaN,NaN,1.0,0.0,1.0,0.0,0.0,1.0,NaN,10.0,5bfef9ecb211ec4f518cfc1d2a6f3e0c,21db37adb60cdcafadfa7dca1b13b6b1,NaN,0.0,0.0,0.0,NaN,Within 7 to 12 months,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,work for a nonprofit,1.0,Full-Stack Web Developer,in an office with other developers,English,"single, never married",80.0,6.0,f8f8be6910,2017-03-09 00:37:07,2017-03-09 00:33:26,2017-03-09 00:38:59,2017-03-09 00:37:10,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,"some college credit, no degree",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21.0,0.0,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15 to 29 minutes,United States of America,United States of America,software development and IT,NaN,Employed for wages,NaN,70000.0,NaN,NaN,male,NaN,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,25.0,14f1863afa9c7de488050b82eb3edd96,21ba173828fbe9e27ccebaf4d5166a55,13000.0,1.0,0.0,0.0,0.0,Within 7 to 12 months,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,work for a medium-sized company,1.0,"Front-End Web Developer, Back-End Web Develo...",no preference,Spanish,"single, never married",1000.0,5.0,2ed189768e,2017-03-09 00:37:58,2017-03-09 00:33:53,2017-03-09 00:40:14,2017-03-09 00:38:02,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Codenewbie,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,high school diploma or equivalent (GED),NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I work from home,Brazil,Brazil,software development and IT,NaN,Employed for wages,NaN,40000.0,0.0,NaN,male,NaN,0.0,1.0,1.0,1.0,1.0,0.0,0.0,40000.0,14.0,91756eb4dc280062a541c25a3d44cfb0,3be37b558f02daae93a6da10f83f0c77,24000.0,0.0,0.0,0.0,1.0,Within the next 6 months,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,work for a medium-sized company,NaN,"Front-End Web Developer, Full-Stack Web Deve...",from home,Portuguese,married or domestic partnership,0.0,5.0,dbdc0664d1,2017-03-09 00:40:13,2017-03-09 00:37:45,2017-03-09 00:42:26,2017-03-09 00:40:18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portugal,Portugal,NaN,NaN,Not working but looking for work,NaN,140000.0,NaN,NaN,female,NaN,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,10.0,aa3f061a1949a90b27bef7411ecd193f,d7c56bbf2c7b62096be9db010e86d96d,NaN,0.0,0.0,0.0,NaN,Within 7 to 12 months,1.0,NaN,NaN,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,work for a multinational corporation,1.0,"Full-Stack Web Developer, Information Security...",in an office with other developers,Portuguese,"single, never married",0.0,24.0,11b0f2d8a9,2017-03-09 00:42:45,2017-03-09 00:39:44,2017-03-09 00:45:42,2017-03-09 00:42:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,bachelor's degree,Information Technology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

8. Carregue as planilhas de 2016 e 2017 por nome em variáveis separadas. Calcule a média da coluna Age para as diferentes abas do arquivo.

In [12]:
survey_2016 = pd.read_excel(path_xlsx, sheet_name = ["2016"])
survey_2017 = pd.read_excel(path_xlsx, sheet_name = ["2017"])

In [15]:
list(survey_2016['2016'])

['Age',
 'AttendedBootcamp',
 'BootcampFinish',
 'BootcampFullJobAfter',
 'BootcampLoanYesNo',
 'BootcampMonthsAgo',
 'BootcampName',
 'BootcampPostSalary',
 'BootcampRecommend',
 'ChildrenNumber',
 'CityPopulation',
 'CodeEventBootcamp',
 'CodeEventCoffee',
 'CodeEventConferences',
 'CodeEventDjangoGirls',
 'CodeEventGameJam',
 'CodeEventGirlDev',
 'CodeEventHackathons',
 'CodeEventMeetup',
 'CodeEventNodeSchool',
 'CodeEventNone',
 'CodeEventOther',
 'CodeEventRailsBridge',
 'CodeEventRailsGirls',
 'CodeEventStartUpWknd',
 'CodeEventWomenCode',
 'CodeEventWorkshop',
 'CommuteTime',
 'CountryCitizen',
 'CountryLive',
 'EmploymentField',
 'EmploymentFieldOther',
 'EmploymentStatus',
 'EmploymentStatusOther',
 'ExpectedEarning',
 'FinanciallySupporting',
 'Gender',
 'HasChildren',
 'HasDebt',
 'HasFinancialDependents',
 'HasHighSpdInternet',
 'HasHomeMortgage',
 'HasServedInMilitary',
 'HasStudentDebt',
 'HomeMortgageOwe',
 'HoursLearning',
 'ID.x',
 'ID.y',
 'Income',
 'IsEthnicMinority',
 'IsReceiveDiabilitiesBenefits',
 'IsSoftwareDev',
 'IsUnderEmployed',
 'JobApplyWhen',
 'JobPref',
 'JobRelocateYesNo',
 'JobRoleInterest',
 'JobRoleInterestOther',
 'JobWherePref',
 'LanguageAtHome',
 'MaritalStatus',
 'MoneyForLearning',
 'MonthsProgramming',
 'NetworkID',
 'Part1EndTime',
 'Part1StartTime',
 'Part2EndTime',
 'Part2StartTime',
 'PodcastChangeLog',
 'PodcastCodeNewbie',
 'PodcastCodingBlocks',
 'PodcastDeveloperTea',
 'PodcastDotNetRocks',
 'PodcastHanselminutes',
 'PodcastJSJabber',
 'PodcastJsAir',
 'PodcastNone',
 'PodcastOther',
 'PodcastProgrammingThrowDown',
 'PodcastRubyRogues',
 'PodcastSEDaily',
 'PodcastShopTalk',
 'PodcastTalkPython',
 'PodcastWebAhead',
 'ResourceBlogs',
 'ResourceBooks',
 'ResourceCodeWars',
 'ResourceCodecademy',
 'ResourceCoursera',
 'ResourceDevTips',
 'ResourceEdX',
 'ResourceEggHead',
 'ResourceFCC',
 'ResourceGoogle',
 'ResourceHackerRank',
 'ResourceKhanAcademy',
 'ResourceLynda',
 'ResourceMDN',
 'ResourceOdinProj',
 'ResourceOther',
 'ResourcePluralSight',
 'ResourceReddit',
 'ResourceSkillCrush',
 'ResourceSoloLearn',
 'ResourceStackOverflow',
 'ResourceTreehouse',
 'ResourceUdacity',
 'ResourceUdemy',
 'ResourceW3Schools',
 'ResourceYouTube',
 'SchoolDegree',
 'SchoolMajor',
 'StudentDebtOwe']

In [16]:
avg_age_2016 = survey_2016['2016']['Age'].mean()
avg_age_2017 = survey_2017['2017']['Age'].mean()
print(f'Média da coluna Age da aba 2016 é igual a {avg_age_2016}')
print(f'Média da coluna Age da aba 2017 é igual a {avg_age_2017}')

Média da coluna Age da aba 2016 é igual a 29.17542055388232
Média da coluna Age da aba 2017 é igual a 27.691872193661744

9. Concatene as diferentes abas do arquivo `fcc_survey.xlsx` em apenas um dataframe. Calcule a média da coluna Age para a concatenação das abas do arquivo.

In [19]:
survey_concat = pd.concat([survey_2016['2016'],survey_2017['2017']])
avg_age_concat = survey_concat['Age'].mean()
print(f'Média da coluna Age no dataframe concatenado é igual a {avg_age_concat}')

Média da coluna Age no dataframe concatenado é igual a 28.388750862663905

10.  Utilizando uma query em SQL e o banco `sqlite-sakila.db` retorne as cidades e os países, mas apenas os países que começem com a letra **B**.

In [22]:
from sqlalchemy import create_engine
from sqlalchemy import inspect

engine = create_engine('sqlite:///../dados/aula3/sqlite-sakila.db')
insp = inspect(engine)
insp.get_table_names()

['actor',
 'address',
 'category',
 'city',
 'country',
 'customer',
 'film',
 'film_actor',
 'film_category',
 'film_text',
 'inventory',
 'language',
 'payment',
 'rental',
 'staff',
 'store']

In [29]:
query = 'select city,country from city a left join country b on a.country_id = b.country_id where substr(country,1,1) = "B"'
city_country = pd.read_sql_query(query, engine)
city_country

                    city     country
0              al-Manama     Bahrain
1               Alvorada      Brazil
2         Angra dos Reis      Brazil
3                Anpolis      Brazil
4    Aparecida de Goinia      Brazil
5               Araatuba      Brazil
6                    Bag      Brazil
7    Bandar Seri Begawan      Brunei
8                   Belm      Brazil
9               Blumenau      Brazil
10             Boa Vista      Brazil
11               Braslia      Brazil
12                 Dhaka  Bangladesh
13               El Alto     Bolivia
14                Goinia      Brazil
15                Guaruj      Brazil
16   guas Lindas de Gois      Brazil
17                Ibirit      Brazil
18              Jamalpur  Bangladesh
19     Juazeiro do Norte      Brazil
20          Juiz de Fora      Brazil
21               Luzinia      Brazil
22                Maring      Brazil
23              Mogiljov     Belarus
24             Molodetno     Belarus
25                    Po      Brazil
26        Poos de Caldas      Brazil
27             Rio Claro      Brazil
28                  Ruse    Bulgaria
29   Santa Brbara dOeste      Brazil
30            Santo Andr      Brazil
31  So Bernardo do Campo      Brazil
32           So Leopoldo      Brazil
33              Sorocaba      Brazil
34          Stara Zagora    Bulgaria
35                 Sucre     Bolivia
36               Tangail  Bangladesh
37            Vila Velha      Brazil
38  Vitria de Santo Anto      Brazil